SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

DROP SCHEMA IF EXISTS `projekat_baze_podataka`;
CREATE SCHEMA IF NOT EXISTS `projekat_baze_podataka` DEFAULT CHARACTER SET utf8;
USE `projekat_baze_podataka`;

CREATE TABLE IF NOT EXISTS `Zaposleni` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Ime` VARCHAR(45) NOT NULL,
  `Prezime` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `Agent` (
  `ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_ID_Agent`
    FOREIGN KEY (`ID`) REFERENCES `Zaposleni` (`ID`)
    ON DELETE CASCADE ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `Servisni_tehnicar` (
  `ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_ID_ServisniTehnicar`
    FOREIGN KEY (`ID`) REFERENCES `Zaposleni` (`ID`)
    ON DELETE CASCADE ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `Vozilo` (
  `VIN` CHAR(17) NOT NULL,
  `Marka` VARCHAR(45) NOT NULL,
  `Model` VARCHAR(45) NOT NULL,
  `Godiste` INT NOT NULL,
  `Boja` VARCHAR(20) NOT NULL,
  `Opis` VARCHAR(250) NULL,
  PRIMARY KEY (`VIN`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `Tehnicka_Specifikacija` (
  `VIN` CHAR(17) NOT NULL,
  `Kilometraza` INT NOT NULL,
  `ZapreminaMotora` INT NOT NULL,
  `VrstaGoriva` VARCHAR(10) NOT NULL,
  `Pogon` VARCHAR(20) NOT NULL,
  `Oprema` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`VIN`),
  CONSTRAINT `FK_VIN_TehnickaSpecifikacija`
    FOREIGN KEY (`VIN`) REFERENCES `Vozilo` (`VIN`)
    ON DELETE CASCADE ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `Komercijalni_Podaci` (
  `VIN` CHAR(17) NOT NULL,
  `NabavnaCijena` DECIMAL(10,2) NOT NULL,
  `ProdajnaCijena` DECIMAL(10,2) NOT NULL,
  `Status` ENUM('Dostupno', 'Rezervisano', 'Prodano') NOT NULL,
  PRIMARY KEY (`VIN`),
  CONSTRAINT `FK_VIN_KomercijalniPodaci`
    FOREIGN KEY (`VIN`) REFERENCES `Vozilo` (`VIN`)
    ON DELETE CASCADE ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `Novo_Vozilo` (
  `VIN` CHAR(17) NOT NULL,
  `PeriodGarancije` INT NOT NULL,
  PRIMARY KEY (`VIN`),
  CONSTRAINT `FK_VIN_NovoVozilo`
    FOREIGN KEY (`VIN`) REFERENCES `Vozilo` (`VIN`)
    ON DELETE CASCADE ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `Polovno_Vozilo` (
  `VIN` CHAR(17) NOT NULL,
  `BrojPrethodnihVlasnika` INT NOT NULL,
  PRIMARY KEY (`VIN`),
  CONSTRAINT `FK_VIN_PolovnoVozilo`
    FOREIGN KEY (`VIN`) REFERENCES `Vozilo` (`VIN`)
    ON DELETE CASCADE ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `Kupac` (
  `JMB` CHAR(13) NOT NULL,
  `Ime` VARCHAR(45) NOT NULL,
  `Prezime` VARCHAR(45) NOT NULL,
  `Adresa` VARCHAR(45) NOT NULL,
  `Telefon` VARCHAR(15) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`JMB`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `Placanje` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Tip` ENUM('Kredit', 'Gotovina', 'Lizing') NOT NULL,
  `Banka` VARCHAR(45) NULL,
  `BrojRata` INT NULL,
  `IznosRate` DECIMAL(10,2) NULL,
  `Avans` DECIMAL(10,2) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `Prodaja` (
  `IdProdaje` INT NOT NULL AUTO_INCREMENT,
  `ID_Agenta` INT NOT NULL,
  `JMB_Kupca` CHAR(13) NOT NULL,
  `VIN` CHAR(17) NOT NULL,
  `ID_Placanja` INT NOT NULL,
  `Datum` DATE NOT NULL,
  `Cijena` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`IdProdaje`),
  CONSTRAINT `FK_ID_Agenta_Prodaja`
    FOREIGN KEY (`ID_Agenta`) REFERENCES `Agent` (`ID`)
    ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_JMB_Kupca_Prodaja`
    FOREIGN KEY (`JMB_Kupca`) REFERENCES `Kupac` (`JMB`)
    ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_VIN_Prodaja`
    FOREIGN KEY (`VIN`) REFERENCES `Vozilo` (`VIN`)
    ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_ID_Placanja_Prodaja`
    FOREIGN KEY (`ID_Placanja`) REFERENCES `Placanje` (`ID`)
    ON DELETE NO ACTION ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `Testna_Voznja` (
  `VIN` CHAR(17) NOT NULL,
  `JMB_Kupca` CHAR(13) NOT NULL,
  `ID_Agenta` INT NOT NULL,
  `DatumVoznje` DATE NOT NULL,
  PRIMARY KEY (`VIN`, `JMB_Kupca`, `ID_Agenta`, `DatumVoznje`),
  CONSTRAINT `FK_JMB_Kupca_TestnaVoznja`
    FOREIGN KEY (`JMB_Kupca`) REFERENCES `Kupac` (`JMB`)
    ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_ID_Agenta_TestnaVoznja`
    FOREIGN KEY (`ID_Agenta`) REFERENCES `Agent` (`ID`)
    ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_VIN_TestnaVoznja`
    FOREIGN KEY (`VIN`) REFERENCES `Vozilo` (`VIN`)
    ON DELETE NO ACTION ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `Uplata` (
  `IdUplate` INT NOT NULL AUTO_INCREMENT,
  `IdPlacanja` INT NOT NULL,
  `Iznos` DECIMAL(10,2) NOT NULL,
  `DatumUplate` DATE NOT NULL,
  PRIMARY KEY (`IdUplate`),
  CONSTRAINT `FK_IdPlacanja_Uplata`
    FOREIGN KEY (`IdPlacanja`) REFERENCES `Placanje` (`ID`)
    ON DELETE NO ACTION ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `Dio` (
  `IdDijela` INT NOT NULL AUTO_INCREMENT,
  `Naziv` VARCHAR(45) NOT NULL,
  `Zaliha` INT NOT NULL,
  `MinimalnaKolicina` INT NOT NULL,
  PRIMARY KEY (`IdDijela`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `Radni_Nalog` (
  `IdNaloga` INT NOT NULL AUTO_INCREMENT,
  `VIN` CHAR(17) NOT NULL,
  `JMB_Vlasnika` CHAR(13) NOT NULL,
  `IdTehnicara` INT NOT NULL,
  `OpisZahtjeva` VARCHAR(250) NOT NULL,
  `DatumPrijema` DATE NOT NULL,
  `Status` ENUM('Primljeno', 'U radu', 'Zavrseno', 'Isporuceno') NOT NULL,
  `CijenaRada` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`IdNaloga`),
  CONSTRAINT `FK_ID_RadniNalog`
    FOREIGN KEY (`IdTehnicara`) REFERENCES `Servisni_tehnicar` (`ID`)
    ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_VIN_RadniNalog`
    FOREIGN KEY (`VIN`) REFERENCES `Vozilo` (`VIN`)
    ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_JMB_Vlasnika_RadniNalog`
    FOREIGN KEY (`JMB_Vlasnika`) REFERENCES `Kupac` (`JMB`)
    ON DELETE NO ACTION ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `Popravka` (
  `IdNaloga` INT NOT NULL,
  `IdDijela` INT NOT NULL,
  `DatumPopravke` DATE NOT NULL,
  `UtrosenaKolicina` INT NOT NULL,
  `UtrosenoVrijeme` INT NOT NULL,
  PRIMARY KEY (`IdNaloga`, `IdDijela`, `DatumPopravke`),
  CONSTRAINT `FK_IdNaloga_Popravka`
    FOREIGN KEY (`IdNaloga`) REFERENCES `Radni_Nalog` (`IdNaloga`)
    ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_IdDijela_Popravka`
    FOREIGN KEY (`IdDijela`) REFERENCES `Dio` (`IdDijela`)
    ON DELETE NO ACTION ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `Racun` (
  `IdNaloga` INT NOT NULL,
  `Iznos` DECIMAL(10,2) NOT NULL,
  `DatumIzdavanja` DATE NOT NULL,
  PRIMARY KEY (`IdNaloga`),
  CONSTRAINT `FK_IdNaloga_Racun`
    FOREIGN KEY (`IdNaloga`) REFERENCES `Radni_Nalog` (`IdNaloga`)
    ON DELETE NO ACTION ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `Dobavljac` (
  `IdDobavljaca` INT NOT NULL AUTO_INCREMENT,
  `Naziv` VARCHAR(45) NOT NULL,
  `Adresa` VARCHAR(45) NOT NULL,
  `Telefon` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`IdDobavljaca`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `Narudzba` (
  `IdNarudzbe` INT NOT NULL AUTO_INCREMENT,
  `IdDobavljaca` INT NOT NULL,
  `DatumNarudzbe` DATE NOT NULL,
  `Status` ENUM('Naruceno', 'Primljeno') NOT NULL,
  PRIMARY KEY (`IdNarudzbe`),
  CONSTRAINT `FK_IdDobavljaca_Narudzba`
    FOREIGN KEY (`IdDobavljaca`) REFERENCES `Dobavljac` (`IdDobavljaca`)
    ON DELETE NO ACTION ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `Stavka` (
  `IdDijela` INT NOT NULL,
  `IdNarudzbe` INT NOT NULL,
  `Cijena` DECIMAL(10,2) NOT NULL,
  `Kolicina` INT NOT NULL,
  PRIMARY KEY (`IdDijela`, `IdNarudzbe`),
  CONSTRAINT `FK_IdDijela_Stavka`
    FOREIGN KEY (`IdDijela`) REFERENCES `Dio` (`IdDijela`)
    ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_IdNarudzbe_Stavka`
    FOREIGN KEY (`IdNarudzbe`) REFERENCES `Narudzba` (`IdNarudzbe`)
    ON DELETE NO ACTION ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;